/*
 * This is a bringing together of all biometrics types used in the kyc app.
 * It currently is made up of DocType, MiscCaptureType and FingersEnum enums.
 */
package com.sf.biocapture.entity.enums;

/**
 *
 * @author wizzyclems
 */
public enum SfxCrmTypes
{    
    
    PORTRAIT("CUSTOMER PORTRAIT"),
    SIM_SWAP_FORM("CUSTOMER SIM SWAP PORTRAIT"),
    
    RIGHT_THUMB("RIGHT THUMB"),
    RIGHT_THUMB_FINGER("RIGHT THUMB FINGER"),
    RIGHT_INDEX("RIGHT INDEX"),
    RIGHT_INDEX_FINGER("RIGHT INDEX FINGER"),
    RIGHT_MIDDLE("RIGHT MIDDLE"),
    RIGHT_MIDDLE_FINGER("RIGHT MIDDLE FINGER"),
    RIGHT_RING("RIGHT RING"),
    RIGHT_RING_FINGER("RIGHT RING FINGER"),
    RIGHT_LITTLE("RIGHT LITTLE"),
    RIGHT_LITTLE_FINGER("RIGHT LITTLE FINGER"),
    RIGHT_PINKY("RIGHT PINKY"),
    
    LEFT_THUMB("LEFT THUMB"),
    LEFT_THUMB_FINGER("LEFT THUMB FINGER"),
    LEFT_INDEX("LEFT INDEX"),
    LEFT_INDEX_FINGER("LEFT INDEX FINGER"),
    LEFT_MIDDLE("LEFT MIDDLE"),
    LEFT_MIDDLE_FINGER("LEFT MIDDLE FINGER"),
    LEFT_RING("LEFT RING"),
    LEFT_RING_FINGER("LEFT RING FINGER"),
    LEFT_LITTLE("LEFT LITTLE"),
    LEFT_LITTLE_FINGER("LEFT LITTLE FINGER"),
    LEFT_PINKY("LEFT PINKY"),
    
    MISSING_FINGER("MISSING FINGER"),
    MISSING_RIGHT_HAND("MISSING RIGHT HAND"),
    MISSING_LEFT_HAND("MISSING LEFT HAND"),
    PASSPORT("INTERNATIONAL PASSPORT"),
    REGISTRATION_FORM("REGISTRATION FORM"),
    KYC_FORM("KYC FORM"),
    MODE_OF_IDENTIFICATION("MODE OF IDENTIFICATION"),
    
    CERTIFICATE_OF_INCORPORATION("CERTIFICATE OF INCORPORATION"), 
    CONTACT_PERSON_FORM("CONTACT PERSON FORM"),
    BANK_GUARANTEE_LETTER("BANK GUARANTEE LETTER"), 
    PASSPORT_PHOTOGRAPHS("PASSPORT PHOTOGRAPHS"), 
    SIGNATURE_CARD("SIGNATURE CARD"),
    REQUEST_LETTER("REQUEST LETTER"), 
    UTILITY_BILL("UTILITY BILL"), 
    EVIDENCE_OF_PAYMENT("EVIDENCE OF PAYMENT"),
    
    
    DRIVERS_LICENSE("Drivers License"),
    DRIVING_LICENCE("DRIVING LICENCE"),
    NATIONAL_ID_CARD("National ID Card"),
    INTERNATIONAL_PASSPORT("International Passport"),
    RESIDENCE_PERMIT("RESIDENCE PERMIT"),
    TRAVEL_DOCUMENT("TRAVEL DOCUMENT"),
    NATIONAL_ID("NATIONAL ID"),
    NATIONAL_DRIVERS_LICENSE("NATIONAL DRIVERS LICENSE"),
    VOTERS_CARD("Voters Card"),
    OTHER("Other"),
    OTHERS("Others");
    
    String value;

    SfxCrmTypes(String type) {
        value = type;
    }

    public String getValue() {
        return value;
    }
}
